Added optionsFunction to allow for dynamic options
jaredhanson/passport-oauth2 pull request #120
Opened 2020-03-12 01:28 UTC by corbettbarr

In multi-tenant environments, the optionsFunction will be called during passport.authenticate so options can be created dynamically based on incoming request.

optionsFunction should be provided in constructor options object, and return authorizationURL, tokenURL and clientID. callbackURL and sessionKey must be provided as static values in options object.

2020-07-15 17:56 UTC, corbettbarr commented
No @Bnaya I haven't released it as a package, but feel free to do so if you'd like. This PR is a fairly small set of changes.

2020-11-30 21:15 UTC, brodly commented
Whats the status on merging this PR? Would love to use this feature... currently using it on SAML and need similar functionality for Oauth.

2020-11-30 22:24 UTC, brodly requested changes
Removed es6 functions as they wont compile for < node 3 builds

2020-11-30 22:24 UTC, brodly commented on test/oauth2.test.js
> +            optionsFunction: () => {
```suggestion
            optionsFunction: function() { 
```

remove es6 syntax for <= node 3

2020-11-30 22:24 UTC, brodly commented on test/oauth2.test.js
> +            optionsFunction: () => {
```suggestion
            optionsFunction: function() { 
```
remove es6 syntax

2020-11-30 22:24 UTC, brodly commented on test/oauth2.test.js
> +        optionsFunction: (req, cb) => {
```suggestion
        optionsFunction: function(req, cb) { 
```

2020-11-30 22:24 UTC, brodly commented on test/oauth2.test.js
> +        optionsFunction: (req, cb) => {
```suggestion
        optionsFunction: function(req, cb) { 
```

2020-11-30 22:24 UTC, brodly commented on test/oauth2.test.js
> +        optionsFunction: (req, cb) => {
```suggestion
        optionsFunction: function(req, cb) { 
```

2020-11-30 22:24 UTC, brodly commented on test/oauth2.test.js
> +        optionsFunction: (req, cb) => {
```suggestion
        optionsFunction: function(req, cb) { 
```

2021-07-01 17:36 UTC, jaredhanson commented
I'm declining to merge this PR, as this functionality is already achievable at the `passport` level and duplicating `optionsFunction` functionality across protocol-specific strategies (OAuth 2.0, SAML, OIDC, etc) would be redundant.

To achieve this at the passport level, rather than statically `use()`ing strategies ahead of time, create them dynamically during request processing.   For example:

```js
app.get('/login/oauth2', function(req, res, next) {
  var strategy = createStrategy(req.query.provider);
  passport.authenticate(strategy)(req, res, next);
});

function createStrategy(provider) {
  var clientID, clientSecret; // Load these from config store based on provider.

  return new OAuth2Strategy({
      clientID: clientID,
      clientSecret: clientSecret,
      callbackURL: '/oauth2/callback',
    },
    function(accessToken, refreshToken, profile, cb) {
      // ...
    });
}
```

More information can be found on the blog post announcing the feature: [Authenticate using Strategy Instances](https://medium.com/passportjs/authenticate-using-strategy-instances-49e58d96ec8c)

2021-07-01 17:36 UTC, closed without merging